### ISSUE TITLE
The task includes an option with an undefined variable.. 'dict object' has no attribute 'USER'

### ISSUE THREAD

**Issue by sugizo** [saint-hilaire/docksible#16]
**info**
```
env : google colab 
os : ubuntu jammy jellyfish (22.04)
Python : 3.11.11
```

**execute**
```
pip install -U docksible
!docksible user@localhost wordpress
```

**result**
```
TASK [wordpress : Copy the Nginx Configuration] ********************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'dict object' has no attribute 'USER'\n\nThe error appears to be in '/usr/local/lib/python3.11/dist-packages/docksible/project/roles/wordpress/tasks/main.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy the Nginx Configuration\n  ^ here\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=8    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0  
```

n.b.
tested work only when using wsl as root (sudo -i)
wsl as user, face a different error (need a root privilege)

thanks and best regards

**Comment by saint-hilaire** [comment]
Hi thanks, I'll look into this soon... possible duplicate of #15 ... regards

**Comment by saint-hilaire** [comment]
Hi @sugizo 

I just released Docksible v0.7.0, which adds support for running locally. Perhaps you can upgrade, and try running it again. It might fix this issue.

Kind regards

**Comment by sugizo** [comment]
**re execute with docksible-0.7.0**
```
pip install -U docksible
!docksible user@localhost wordpress
```

**still got the same result**
```
TASK [wordpress : Copy the Nginx Configuration] ********************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'dict object' has no attribute 'USER'\n\nThe error appears to be in '/usr/local/lib/python3.11/dist-packages/docksible/project/roles/wordpress/tasks/main.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy the Nginx Configuration\n  ^ here\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=8    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

thanks and best regards

**Comment by sugizo** [comment]
the above command executed 
in colab
as reported 
on first posted
and 
you can see 
in colab 
every shell command executed, 
always start with 
`!`

now here re executed with wsl

**steps in wsl (ubuntu os)**

```
sudo apt update
sudo apt install -y python3.12-venv
python3 -m venv ~/docksible
source ~/docksible/bin/activate
pip install -U docksible
docksible user@localhost wordpress
```

**result in wsl (ubuntu os)**

```
TASK [Gathering Facts] *********************************************************
fatal: [localhost]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"ansible.legacy.setup": {"ansible_facts": {"discovered_interpreter_python": "/home/sugizo/docksible/bin/python3.12"}, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform linux on host localhost is using the discovered Python interpreter at /home/sugizo/docksible/bin/python3.12, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.18/reference_appendices/interpreter_discovery.html for more information."]}}, "msg": "The following modules failed to execute: ansible.legacy.setup\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

best regards

**Comment by saint-hilaire** [comment]
Hi @sugizo 

> **result in wsl (ubuntu os)**
> 
> ```
> TASK [Gathering Facts] *********************************************************
> fatal: [localhost]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"ansible.legacy.setup": {"ansible_facts": {"discovered_interpreter_python": "/home/sugizo/docksible/bin/python3.12"}, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1, "warnings": ["Platform linux on host localhost is using the discovered Python interpreter at /home/sugizo/docksible/bin/python3.12, but future installation of another Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.18/reference_appendices/interpreter_discovery.html for more information."]}}, "msg": "The following modules failed to execute: ansible.legacy.setup\n"}
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
> ```

It looks the problem here is that when you specify the user, Docksible did not ask for the Sudo password, even though it should have.

I just released v0.7.1, which includes a bugfix for this. If you upgrade to Docksible v0.7.1, rerun the same command in WSL, then it should ask you for the Sudo password, and run successfully.

Kind regards

**Comment by sugizo** [comment]
**steps in wsl (ubuntu n debian os), run smoothly**

```
sudo apt update
sudo apt install -y python3-venv
python3 -m venv ~/docksible
source ~/docksible/bin/activate
pip install -U docksible
docksible user@localhost wordpress
sudo docker images -a
sudo docker ps -a
```

**execute on another cmd**
`start http://localhost`

**steps in colab with docksible 0.7.1, still have the same result on 1st posted**
```
pip install -U docksible
!docksible user@localhost wordpress
```

**result in colab**
```
TASK [wordpress : Copy the Nginx Configuration] ********************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'dict object' has no attribute 'USER'\n\nThe error appears to be in '/usr/local/lib/python3.11/dist-packages/docksible/project/roles/wordpress/tasks/main.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy the Nginx Configuration\n  ^ here\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=8    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

thanks n best regards

**Comment by saint-hilaire** [comment]
Hi @sugizo 

I just released v0.8.1 which contains a bugfix that I believe will fix this problem:

> **result in colab**
> 
> ```
> TASK [wordpress : Copy the Nginx Configuration] ********************************
> fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable.. 'dict object' has no attribute 'USER'\n\nThe error appears to be in '/usr/local/lib/python3.11/dist-packages/docksible/project/roles/wordpress/tasks/main.yml': line 17, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy the Nginx Configuration\n  ^ here\n"}
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=11   changed=8    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
> ```

Could you please upgrade, try again, and let me know how it goes?

By the way, when the host is `localhost` or `127.0.0.1`, you don't have to specify the user - so you can simply run `docksible localhost wordpress` for example.

Thanks and kind regards

**Comment by sugizo** [comment]
**steps in colab with docksible 0.8.1**
```
pip install -U docksible
!docksible localhost wordpress
```

**result**
```
TASK [wordpress : Run WordPress] ***********************************************
fatal: [localhost]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 1, "stderr": "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n", "stderr_lines": ["Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=13   changed=10   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

**execute**
`!service docker status`

**result**
`Docker is not running`

**execute**
`!service docker start`

**result**
`mkdir: cannot create directory ‘cpuset’: Read-only file system`

thanks and best regards

**Comment by saint-hilaire** [comment]
Hi @sugizo 

Thanks for the feedback. It looks like at least the Ansible user issue was resolved, I will edit the ticket accordingly.

Regarding the Docker daemon issue: I am facing the same issue when I try to run in WSL. I might be able to fix this at some point in the future, but it will take a while, because IMO this is an edge case, and thus lower priority. It would be cool if we can get it to work, but Docksible is not intended to run on exotic environments like WSL or Google Colab. It is designed to install public facing web apps on cloud infrastructure, or alternatively, on a Linux host in internal networks. I'm not too familiar with Google Colab, but from what I can tell, it's a product for data science, and thus the wrong tool.

Perhaps these suggestions might help you:

* Since you use Google Colab, do you have access to the GCP platform in general? If you do, you could order an inexpensive VPS, which is exactly what Docksible is designed for. Personally, I use mainly DigitalOcean, but these cloud platforms are very similar, and I think GCP should work well too.
* If you're running locally, then instead of WSL, you could set up an Ubuntu VM with VirtualBox, QEMU/KVM, VMware, or similar.

I believe that in both of those setups, Docksible will work much better than on Google Colab or WSL.

Nonetheless, I'd be happy to get this particular issue resolved. I will stop working on this, and focus on other things, but I will add the **help wanted** and **good first issue** labels to invite other developers to contribute. Naturally, you're welcome to contribute too! If you can implement a fix for this bug, I'd be happy to include it in a future release, just branch out of the `develop` branch and let me know if you have questions.

Thanks and kind regards

**Comment by saint-hilaire** [comment]
For future reference: the commented block in the `setup-docker-compose` role might help fix this.
